# Generated by Django 5.1.4 on 2024-12-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_cateringrequest_remove_order_food_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(default='images/placeholder.jpg', upload_to='food_images/'),
        ),
    ]
