# Generated by Django 5.1.4 on 2024-12-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0004_rename_fooditem_orderitem_food_tem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='food_tem',
            new_name='food_item',
        ),
    ]
