# Generated by Django 5.1.4 on 2024-12-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0005_rename_food_tem_orderitem_food_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringrequest',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
